jobs:
  hello:
    requires: [~commit,pr]
    image: alpine:latest
    steps:
      - greet: echo "Hello from ray1 test2"

  build:
    requires: [~commit,~pr]
    image: alpine:latest
    steps:
      - greet: echo "Hello from ray24"

  test-branch-job:
    requires: [~commit:feat/test]  # This job triggers only when commits are pushed to the 'test' branch
    image: alpine:latest
    steps:
      - greet: echo "Hello from the test branch!. How are you ? tteaisatuhaha test"
