jobs:
  main:
    requires: [~commit, ~pr]
    image: ubuntu:latest
    steps:
      - check-version: cat /etc/os-releasejobs:
  main:
    requires: [~commit, ~pr]
    image: ubuntu:latest
    steps:
      - check-version: cat /etc/os-release
